CREATE TABLE "Case" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "identifyingTerms" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
